# Generated by Django 5.2.5 on 2025-10-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_countyzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='revenue.countyzone'),
            preserve_default=False,
        ),
    ]
